# Generated by Django 4.1.3 on 2023-07-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo_title", models.TextField(max_length=50)),
                ("todo_data_created", models.DateTimeField(auto_now=True)),
                ("todo_data_updated", models.DateTimeField(auto_now_add=True)),
                ("todo_text", models.TextField(max_length=250)),
                ("todo_published", models.BooleanField(default=True)),
            ],
        ),
    ]
